#MySQL database settings

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enver
    username: postgres
    password: Aa123456!
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          envers:
            audit_table_suffix: _HISTORY
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false


